import fs from "fs";
import path from "path";

export type UdpHostsFile = {
  hosts: { host: string; status: string }[];
};

/**
 * Current DNS list from file generated by hosts/sync-udp6540-hosts.py
 * (run: npm run sync:udp6540). Read from disk without a full Next rebuild.
 */
export function loadUdpHostsJson(): UdpHostsFile {
  const p = path.join(process.cwd(), "src/data/udp6540-hosts.json");
  const raw = fs.readFileSync(p, "utf-8");
  return JSON.parse(raw) as UdpHostsFile;
}
